### ISSUE TITLE
[BUG] App chrome compatibility

### ISSUE THREAD

**Issue by sakdec10** [ConnorMulqueen/Geesenado#56] opened 2018-04-03 23:07 UTC
Hey so i tried the app in chrome and Microsoft edge browser. 
I found that the app ran perfectly in the Edge browser (my surprise) but in chrome I was having some issues, with looks as well as the "pencil" not showing up. Also no health bars.

I was working on chrome v65.0.3325.181 (Official Build) (64-bit) and Edge v41.16299.248.0

I created a video so that you guys can clearly see what I am talking about. First is in Edge then chrome
https://drive.google.com/drive/folders/1Utp7wyU4IpsB3Ny8vKHMHzmGAeiRiPmj?usp=sharing

**Comment by jaredgav** [comment] 2018-04-05 03:06
Could not reproduce. Please retry on browser as it may have been a personal issue. Closing as non-issue

**Closed by jaredgav** 2018-04-05 03:06 UTC
